export enum RoutingPath {
    OVERVIEW = 'overview',
    FOLDER = 'folder',
    COLLECTIBLES = 'collectibles',
    BRIDGE = 'bridge',
    SAVINGS = 'savings',
    HUBSOL = 'hubSOL',
    LOYALTY_LEAGUE = 'loyalty-league',
    SWAP = 'swap',
    STAKING = 'staking',
    LENDING = 'lending',
    LIQUIDITY_POOLS = 'liquidity-pools',
    DAO = 'dao',
    AIRDROP_FINDER = 'airdrop-finder',
    NOTIFICATIONS = 'notifications',
    SETTINGS = 'settings',
    EVENTS = 'events',
}
